=head1 NAME

Finance::Optical::StrongBuy;

=head1 DBI


=head1 AVOID RECALCULATING


#!/usr/bin/perl
package main;

use Data::Dumper;
use Finance::Optical::StrongBuy;
use Finance::NASDAQ::Markets;
use Finance::Google::Sector::Mean;




my @sector = sectorsummary();

my @idx = index();

my @sec = sector();



my $new = Finance::Optical::StrongBuy->new("/tmp");
foreach my $symbol (qw/C BAC WFC WM F GE AAPL GOOG/){
    $new->callCheck($symbol);
}

print Dumper [@idx,@sec,@sector ,$new];


1;

